# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv

## data was not found at this link, Downloaded from gdrive and placed in data/
source_data_url: https://common-data-001.s3.ap-south-1.amazonaws.com/aiops-class-demo-data/data.xml


source_download_dir:
  data_dir: data
  data_file: data.xml

local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
